/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_projects__project_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Project */
        get: operations["export_project_projects__project_id__export_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Batches
         * @description This project's batches, newest first — the run history.
         *
         *     Without this, a batch's per-link outcomes were only ever visible in the
         *     browser tab that submitted it: a reload lost them, and with them the typed
         *     failure reasons P§8 promises stay visible. The rows themselves have always
         *     been durable in `ops.sqlite`; only a way to list them was missing.
         */
        get: operations["list_batches_projects__project_id__batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_projects__project_id__batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_projects__project_id__batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/batches/{batch_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Links */
        get: operations["get_batch_links_projects__project_id__batches__batch_id__links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/batches/{batch_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_projects__project_id__batches__batch_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/batches/{batch_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Batch */
        get: operations["stream_batch_projects__project_id__batches__batch_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quota */
        get: operations["get_quota_quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_projects__project_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description One document by id — what a chat citation's doc_id links to.
         */
        get: operations["get_document_projects__project_id__documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Volume
         * @description Documents captured per day, broken down by source (never merged
         *     into one undifferentiated line — EV-P4-04).
         */
        get: operations["volume_projects__project_id__analytics_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_projects__project_id__analytics_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sentiment
         * @description The lexicon *prior* only (VADER, Phase 2 local enrichment) —
         *     structurally its own field (`sentiment_prior_breakdown`), never a
         *     generic "sentiment" name, so a future LLM-derived label can never be
         *     silently merged into this chart (EV-P4-05, A§11.2).
         */
        get: operations["sentiment_projects__project_id__analytics_sentiment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ratings */
        get: operations["ratings_projects__project_id__analytics_ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Themes
         * @description Top terms by raw frequency — a cheap, local, zero-AI-cost signal
         *     (IP§4's "top themes"), computed entirely in DuckDB.
         */
        get: operations["themes_projects__project_id__analytics_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Failures
         * @description From `ops.sqlite` (A§8.1 taxonomy lives on `links`, not the
         *     warehouse) — a summary of what didn't extract, alongside what did.
         */
        get: operations["failures_projects__project_id__analytics_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/analytics/by-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * By Source
         * @description One block per source, carrying only the dimensions that source
         *     actually provides (`app/sources/profiles.py`).
         *
         *     This exists because a single chart across sources is ambiguous by
         *     construction: App Store rows have a 5-star rating and an app version,
         *     YouTube rows have neither but have a like count and thread via
         *     `parent_id`. Drawing one rating axis over both produced a near-empty
         *     chart, and — where two rating-bearing sources were present — silently
         *     overlapping x-values. A§12's "not directly comparable" rule, applied
         *     to chart *selection* rather than just to labelling (EV-P4-04).
         *
         *     Ratings and engagement appear here and are deliberately absent from
         *     any all-sources view.
         */
        get: operations["by_source_projects__project_id__analytics_by_source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat History */
        get: operations["get_chat_history_projects__project_id__chat_get"];
        put?: never;
        /** Post Chat */
        post: operations["post_chat_projects__project_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source Profiles
         * @description What each source provides. Drives which charts and which document
         *     fields the UI renders, so a rating axis never appears for a source
         *     that has no ratings.
         */
        get: operations["get_source_profiles_sources_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/gate/prototypes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prototypes */
        get: operations["get_prototypes_projects__project_id__gate_prototypes_get"];
        /**
         * Put Prototypes
         * @description Replaces this project's prototypes and re-gates its documents.
         *
         *     Both lists must be non-empty: stage 2 scores `best_keep - best_drop`,
         *     so a missing side makes every score one-sided and pushes the whole
         *     corpus to one band.
         */
        put: operations["put_prototypes_projects__project_id__gate_prototypes_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchSummary */
        BatchSummary: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Link Count */
            link_count: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** BySourceResponse */
        BySourceResponse: {
            meta: components["schemas"]["Meta"];
            /** Sources */
            sources: components["schemas"]["SourceBlock"][];
        };
        /** ChatMessage */
        ChatMessage: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Citations */
            citations: string[] | null;
            /** Created At */
            created_at: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Batch Id */
            batch_id?: string | null;
            /** Source */
            source?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Type */
            type: string;
            /** Text */
            text: string;
            /** Citations */
            citations: string[];
            /** Caveats */
            caveats: {
                [key: string]: boolean;
            };
            /** Evidence Count */
            evidence_count: number;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
        };
        /** DocumentRow */
        DocumentRow: {
            /** Doc Id */
            doc_id: string;
            /** Source */
            source: string;
            /** Doc Type */
            doc_type: string;
            /** Source Url */
            source_url: string;
            /** Subject */
            subject: string | null;
            /** Captured At */
            captured_at: string | null;
            /** Authored At */
            authored_at: string | null;
            /** Text */
            text: string | null;
            /** Lang */
            lang: string | null;
            /** Rating */
            rating: number | null;
            /** Verified Purchase */
            verified_purchase: boolean | null;
            /** Sentiment Prior */
            sentiment_prior: number | null;
            /** Gate Band */
            gate_band: string | null;
            /** Lane */
            lane?: string | null;
            /** Extractor Version */
            extractor_version?: string | null;
            /** Product Id */
            product_id?: string | null;
            /** Variant */
            variant?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Engagement */
            engagement?: {
                [key: string]: unknown;
            } | null;
            /** Engagement Count */
            engagement_count?: number | null;
            /** Engagement Kind */
            engagement_kind?: string | null;
        };
        /** DocumentsResponse */
        DocumentsResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentRow"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * EngagementBlock
         * @description Engagement for ONE source only.
         *
         *     `kind` is the source's own word for the metric — `likes`, `score`,
         *     `helpful`. It is mandatory here, and there is deliberately no
         *     cross-source engagement endpoint: a YouTube like and a Reddit upvote
         *     are different populations with different mechanics, so summing them
         *     would be the fabrication-by-aggregation IP§P4 warns about.
         */
        EngagementBlock: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Covered */
            covered: number;
            /** Total */
            total: number;
            /** Max */
            max: number;
            /** Mean */
            mean: number;
            /** Buckets */
            buckets: components["schemas"]["NamedCount"][];
        };
        /** EngagementSpecOut */
        EngagementSpecOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Extras */
            extras: string[][];
        };
        /** FailureCount */
        FailureCount: {
            /** Failure Code */
            failure_code: string;
            /** Count */
            count: number;
        };
        /** FailuresResponse */
        FailuresResponse: {
            /** Total Links */
            total_links: number;
            /** Data */
            data: components["schemas"]["FailureCount"][];
        };
        /** GateBandCount */
        GateBandCount: {
            /** Band */
            band: string;
            /** Doc Count */
            doc_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinkSummary */
        LinkSummary: {
            /** Link Id */
            link_id: string;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Failure Code */
            failure_code?: string | null;
            /** Job Count */
            job_count?: number | null;
        };
        /** Meta */
        Meta: {
            /** Document Count */
            document_count: number;
            /** Sources */
            sources: string[];
            /** Mixed Source */
            mixed_source: boolean;
            /** Captured From */
            captured_from: string | null;
            /** Captured To */
            captured_to: string | null;
        };
        /** NamedCount */
        NamedCount: {
            /** Name */
            name: string;
            /** Doc Count */
            doc_count: number;
        };
        /** ProfilesResponse */
        ProfilesResponse: {
            /** Profiles */
            profiles: components["schemas"]["SourceProfileOut"][];
            /** Comparable Dimensions */
            comparable_dimensions: string[];
        };
        /** ProjectConfig */
        ProjectConfig: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /**
             * Session Mode
             * @default logged_out
             * @enum {string}
             */
            session_mode: "logged_out" | "operator_session";
            /** Enabled Sources */
            enabled_sources?: string[];
            /** Locales */
            locales?: string[];
            /** Rate Overrides */
            rate_overrides?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Gate */
            gate?: {
                [key: string]: unknown;
            };
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Session Mode */
            session_mode: string;
            /** Batch Count */
            batch_count: number;
            /** Document Count */
            document_count: number;
        };
        /** PrototypesRequest */
        PrototypesRequest: {
            /** Keep */
            keep?: string[];
            /** Drop */
            drop?: string[];
        };
        /** PrototypesResponse */
        PrototypesResponse: {
            /** Keep */
            keep: string[];
            /** Drop */
            drop: string[];
            /** Bands */
            bands: components["schemas"]["GateBandCount"][];
            /** Document Count */
            document_count: number;
            /** Starved */
            starved: boolean;
        };
        /** ProviderBudget */
        ProviderBudget: {
            rpm: components["schemas"]["WindowBudget"];
            tpm: components["schemas"]["WindowBudget"];
            rpd: components["schemas"]["WindowBudget"];
        };
        /** QuotaResponse */
        QuotaResponse: {
            gemini: components["schemas"]["ProviderBudget"];
            groq: components["schemas"]["ProviderBudget"];
            ollama: components["schemas"]["ProviderBudget"];
        };
        /** RatingBucket */
        RatingBucket: {
            /** Rating */
            rating: number;
            /** Doc Count */
            doc_count: number;
        };
        /** RatingCount */
        RatingCount: {
            /** Source */
            source: string;
            /** Rating */
            rating: number;
            /** Doc Count */
            doc_count: number;
        };
        /** RatingSpecOut */
        RatingSpecOut: {
            /** Scale */
            scale: number;
            /** Label */
            label: string;
        };
        /** RatingsResponse */
        RatingsResponse: {
            meta: components["schemas"]["Meta"];
            /** Data */
            data: components["schemas"]["RatingCount"][];
        };
        /** SentimentBucket */
        SentimentBucket: {
            /** Source */
            source: string;
            /** Bucket */
            bucket: string;
            /** Doc Count */
            doc_count: number;
        };
        /** SentimentResponse */
        SentimentResponse: {
            meta: components["schemas"]["Meta"];
            /** Sentiment Prior Breakdown */
            sentiment_prior_breakdown: components["schemas"]["SentimentBucket"][];
        };
        /** SourceBlock */
        SourceBlock: {
            /** Source */
            source: string;
            /** Label */
            label: string;
            /** Doc Count */
            doc_count: number;
            /** Captured From */
            captured_from: string | null;
            /** Captured To */
            captured_to: string | null;
            /** Doc Types */
            doc_types: components["schemas"]["NamedCount"][];
            /** Volume */
            volume: components["schemas"]["NamedCount"][];
            /** Lanes */
            lanes: components["schemas"]["NamedCount"][];
            /** Languages */
            languages: components["schemas"]["NamedCount"][];
            /** Sentiment Prior Breakdown */
            sentiment_prior_breakdown: components["schemas"]["NamedCount"][];
            /** Ratings */
            ratings: components["schemas"]["RatingBucket"][];
            /** Rating Coverage */
            rating_coverage: number;
            /** Rating Scale */
            rating_scale: number | null;
            engagement: components["schemas"]["EngagementBlock"] | null;
        };
        /** SourceCount */
        SourceCount: {
            /** Source */
            source: string;
            /** Doc Count */
            doc_count: number;
        };
        /** SourceProfileOut */
        SourceProfileOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Doc Types */
            doc_types: string[];
            rating: components["schemas"]["RatingSpecOut"] | null;
            engagement: components["schemas"]["EngagementSpecOut"] | null;
            /** Threaded */
            threaded: boolean;
            /** Verified Purchase */
            verified_purchase: boolean;
            /** Subject Label */
            subject_label: string | null;
            /** Product Id Label */
            product_id_label: string | null;
            /** Variant Label */
            variant_label: string | null;
            /** Notes */
            notes: string | null;
        };
        /** SourcesResponse */
        SourcesResponse: {
            meta: components["schemas"]["Meta"];
            /** Data */
            data: components["schemas"]["SourceCount"][];
        };
        /** SubmitBatchRequest */
        SubmitBatchRequest: {
            /** Urls */
            urls: string[];
        };
        /** SubmitBatchResponse */
        SubmitBatchResponse: {
            /** Batch Id */
            batch_id: string;
            /** Links */
            links: components["schemas"]["LinkSummary"][];
        };
        /** ThemeCount */
        ThemeCount: {
            /** Term */
            term: string;
            /** Freq */
            freq: number;
        };
        /** ThemesResponse */
        ThemesResponse: {
            meta: components["schemas"]["Meta"];
            /** Data */
            data: components["schemas"]["ThemeCount"][];
        };
        /** UpdateProjectRequest */
        UpdateProjectRequest: {
            /** Session Mode */
            session_mode?: ("logged_out" | "operator_session") | null;
            /** Enabled Sources */
            enabled_sources?: string[] | null;
            /** Locales */
            locales?: string[] | null;
            /** Rate Overrides */
            rate_overrides?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /** Gate */
            gate?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumePoint */
        VolumePoint: {
            /** Day */
            day: string;
            /** Source */
            source: string;
            /** Doc Count */
            doc_count: number;
        };
        /** VolumeResponse */
        VolumeResponse: {
            meta: components["schemas"]["Meta"];
            /** Data */
            data: components["schemas"]["VolumePoint"][];
        };
        /** WindowBudget */
        WindowBudget: {
            /** Used */
            used: number;
            /** Limit */
            limit: number | null;
            /** Remaining */
            remaining: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_projects__project_id__export_xlsx_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_projects__project_id__batches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_projects__project_id__batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_projects__project_id__batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_links_projects__project_id__batches__batch_id__links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_projects__project_id__batches__batch_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_batch_projects__project_id__batches__batch_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quota_quota_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaResponse"];
                };
            };
        };
    };
    list_documents_projects__project_id__documents_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
                source?: string | null;
                gate_band?: string | null;
                doc_type?: string | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_projects__project_id__documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_projects__project_id__analytics_volume_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_projects__project_id__analytics_sources_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sentiment_projects__project_id__analytics_sentiment_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ratings_projects__project_id__analytics_ratings_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    themes_projects__project_id__analytics_themes_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    failures_projects__project_id__analytics_failures_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailuresResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    by_source_projects__project_id__analytics_by_source_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BySourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_projects__project_id__chat_get: {
        parameters: {
            query?: {
                batch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_projects__project_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_profiles_sources_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
        };
    };
    get_prototypes_projects__project_id__gate_prototypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_prototypes_projects__project_id__gate_prototypes_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrototypesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrototypesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
