import createClient from "openapi-fetch";
import type { paths } from "./api-types";
import { API_BASE_URL } from "./env";

/**
 * The only HTTP client in the app (A§14.1 rule 4 — HTTP + SSE only, no
 * shared filesystem, no Python imports). Typed against the FastAPI
 * OpenAPI schema (`api-types.ts`, generated by `pnpm run gen:api`), so
 * the backend contract is enforced by the compiler, not by discipline.
 */
export const api = createClient<paths>({ baseUrl: API_BASE_URL });

export type ProjectConfig =
  paths["/projects"]["post"]["responses"][201]["content"]["application/json"];

export type ProjectSummary =
  paths["/projects"]["get"]["responses"][200]["content"]["application/json"][number];

export type LinkSummary =
  paths["/projects/{project_id}/batches"]["post"]["responses"][202]["content"]["application/json"]["links"][number];

export type SubmitBatchResponse =
  paths["/projects/{project_id}/batches"]["post"]["responses"][202]["content"]["application/json"];

export function sseUrl(projectId: string, batchId: string, sinceId?: number): string {
  const url = new URL(
    `/projects/${projectId}/batches/${batchId}/stream`,
    API_BASE_URL
  );
  if (sinceId !== undefined) url.searchParams.set("since", String(sinceId));
  return url.toString();
}

/**
 * The Excel export is a real file download, so it is an `href` the browser
 * fetches itself — not a `fetch()` + blob + synthetic click. That keeps the
 * download resumable, shows native progress, and means a large export never
 * has to sit in a JS heap first.
 */
export function exportUrl(projectId: string, batchId?: string | null): string {
  const url = new URL(`/projects/${projectId}/export.xlsx`, API_BASE_URL);
  if (batchId) url.searchParams.set("batch_id", batchId);
  return url.toString();
}
